apiVersion: v1
kind: Service
metadata:
  name: synaps-verifier
  namespace: archway
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 2345
      targetPort: 2345
  selector:
    app.kubernetes.io/name: synaps-verifier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synaps-verifier
  namespace: archway
  labels:
    app.kubernetes.io/name: synaps-verifier
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: synaps-verifier
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: synaps-verifier
    spec:
      containers:
        - name: synaps-verifier
          image: synaps-verifier:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
            - containerPort: 2345
              name: tools
          env:
            - name: SYNAPS_VERIFIER_SERVING_ADDR
              value: SYNAPS_VERIFIER_SERVING_ADDR_value
            - name: KYC_API_KEY
              value: KYC_API_KEY_value
            - name: KYC_CLIENT_ID
              value: KYC_CLIENT_ID_value
            - name: KYC_API_PATH
              value: KYC_API_PATH_value
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synaps-verifier
  namespace: archway
  labels:
    app.kubernetes.io/name: synaps-verifier
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: kyc.archway.tech
      http:
        paths:
          - backend:
              service:
                name: synaps-verifier
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - kyc.archway.tech
      secretName: synaps-verifier-cert

