# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and Publish Docker image

on:
  push:
    branches: [main]

jobs:
  deploy-kyc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "KYC_API_KEY"
          replace: ${{ secrets.KYC_API_KEY_VALUE }}
          include: "ci/kyc.yaml"

      - name: Deploy Chain
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.GKE_TENDERMINT_DEV_US_EAST1_STARPORT_CLOUD_DEV_KUBECONFIG_B64 }}
          command: apply -n archway -f ci/kyc.yaml
